### ISSUE TITLE
[Bug] Minecraft 1.21.1 (with Fabric mod loader) crashes when trying to launch the game

### ISSUE THREAD

**Issue by Arc8ne** [Pitan76/MCPitanLib#16]
Link to the Pastebin containing the crash log: https://pastebin.com/WwGAZCCV

## Description
This bug occurred when I was launching Minecraft 1.21.1 (with the Fabric mod loader).

- **Minecraft Version**: 1.21.1
- **ModLoader**: Fabric
- **MCPitanLib Version**: 2.5.0

## Steps to Reproduce
1. Install the following mods:
  - Advanced XRay (Fabric) (Version: 21.0.0)
  - Architectury (Version: 13.0.6)
  - CC: Tweaked (Version: 1.113.1)
  - Fabric API (Version: 0.105.0+1.21.1)
  - Item Alchemy (Version: 1.0.5)
  - Litematica (Version: 0.19.50)
  - MaLiLib (Version: 0.21.0)
  - MCPitanLib (Version: 2.5.0-1.21-fabric)
  - Xaero's Minimap (Version: 24.4.0)
 2. Try launching Minecraft.

## Expected Behavior
I expected Minecraft to not crash when trying to launch it.

**Comment by Knito58** [comment]
MC version 1.20.1 Fabric  [pastebin crash log](https://pastebin.com/57DKWL2G)

2.5.0 works on SP but prevents my server from starting up.
2.4.9 is fine on all systems
Overlapping mod with @Arc8ne is Architectury API 9.2.14+fabric
```

[08:04:58] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mcpitanlib' at 'net.pitan76.mcpitanlib.fabric.MCPitanLibFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.5.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc-1.20.1-loader-0.16.5-launcher-1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_310
	at net.pitan76.mcpitanlib.api.network.v2.ClientNetworking.registerReceiver(ClientNetworking.java:15) ~[mcpitanlib-2.5.0-1.20.1-fabric.jar:?]

```

**Comment by Arc8ne** [comment]
After updating this mod (MCPitanLib) from 2.5.0 to 2.5.1, this bug no longer occurs.

**Comment by Knito58** [comment]
For Fabric 1.20.1 it is not yet visible in the Modrinth app. I'd like to test it.

**Comment by Knito58** [comment]
And 2.5.1 is visible and it works on the server. Bug fix confirmed.
Thank you!
